AllCops:
  TargetRubyVersion: 2.6

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Style/Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false

Metrics/BlockLength:
  CountComments: true
  Max: 25
  Exclude:
    - 'spec/**/*'
    - 'config/**/*'
    - 'lib/tasks/**/*'

Style/FrozenStringLiteralComment:
  Description: >-
    Add the frozen_string_literal comment to the top of files
    to help transition from Ruby 2.3.0 to Ruby 3.0.
  Enabled: false
